version: 2
updates:
  # Enable version updates for npm
  - package-ecosystem: 'npm'
    directory: '/'
    schedule:
      interval: 'weekly'
      day: 'monday'
      time: '04:00'
    open-pull-requests-limit: 10
    reviewers:
      - 'KRDS-MCP/maintainers'
    labels:
      - 'dependencies'
      - 'npm'
    commit-message:
      prefix: 'chore'
      include: 'scope'
    ignore:
      # Ignore major version updates for critical packages
      - dependency-name: '@modelcontextprotocol/sdk'
        update-types: ['version-update:semver-major']
    groups:
      # Group all development dependencies
      dev-dependencies:
        patterns:
          - 'eslint*'
          - 'prettier*'
          - 'jest*'
          - '@types/*'
        update-types:
          - 'minor'
          - 'patch'

  # Enable version updates for GitHub Actions
  - package-ecosystem: 'github-actions'
    directory: '/'
    schedule:
      interval: 'weekly'
      day: 'monday'
      time: '04:00'
    reviewers:
      - 'KRDS-MCP/maintainers'
    labels:
      - 'dependencies'
      - 'github-actions'
    commit-message:
      prefix: 'ci'
      include: 'scope'
